project:
  name: quickstart-boomi-atom
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - us-gov-east-1
  - us-gov-west-1
  - cn-north-1
  - cn-northwest-1
tests:
  quickstart-boomi-atom:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BoomiAccountID: override
      BoomiPassword: override
      BoomiUsername: override
      KeyPairName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 0.0.0.0/0
    regions:
      - us-east-2
    template: templates/boomi-atom-main.template.yaml
