AWSTemplateFormatVersion: "2010-09-09"
Description: Boomi Atom installation script. This creates a VPC, public and private subnets, and deploys a Dell Boomi Atom. (qs-1r0e5j27q)
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into a new VPC
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Network configuration
        Parameters:
         - AvailabilityZones
         - VPCCIDR
         - PublicSubnet1CIDR
         - PublicSubnet2CIDR
         - PrivateSubnet1CIDR
         - PrivateSubnet2CIDR
         - RemoteAccessCIDR
      -
        Label:
          default: Amazon EC2 configuration
        Parameters:
          - InstanceType
          - KeyPairName
          - BoomiInstanceVolumeSize
      -
        Label:
          default: Dell Boomi Atom configuration
        Parameters:
         - AtomName
         - BoomiAccountID
         - BoomiUsername
         - BoomiPassword
         - BoomiInstallDir
         - BoomiInstallToken
      - Label:
          default: AWS Quick Start configuration
        Parameters:      
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
        AvailabilityZones:
          default: Availability Zones
        KeyPairName:
          default: SSH key name
        PrivateSubnet1CIDR:
          default: Private subnet 1 CIDR
        PrivateSubnet2CIDR:
          default: Private subnet 2 CIDR
        PublicSubnet1CIDR:
          default: Public subnet 1 CIDR
        PublicSubnet2CIDR:
          default: Public subnet 2 CIDR
        QSS3BucketName:
          default: Quick Start S3 bucket name
        QSS3BucketRegion:
          default: Quick Start S3 bucket Region
        QSS3KeyPrefix:
          default: Quick Start S3 key prefix
        RemoteAccessCIDR:
          default: Allowed external access CIDR
        VPCCIDR:
          default: VPC CIDR
        InstanceType:
          default: Boomi Atom instance type
        BoomiInstanceVolumeSize:
          default: Amazon EBS volume size of Boomi Atom
        AtomName:
          default: Atom name
        BoomiAccountID:
          default: Boomi account ID
        BoomiUsername:
          default: Boomi user name
        BoomiPassword:
          default: Boomi password
        BoomiInstallDir:
          default: Boomi install directory
        BoomiInstallToken:
          default: Boomi installation token
Parameters:
  KeyPairName:
    Description: Name of the key pair that allows you to connect securely to your instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be an existing name.
  InstanceType:
    Description: Boomi host instance type.
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - r5.xlarge
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
  BoomiInstanceVolumeSize:
    Description: Size of the Amazon EBS volume attached to the Atom instance. Size range is 1GiB–16TiB.
    Type: Number
    Default: 100
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/24
    Description: CIDR block for the public subnet, located in Availability Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.64.0/24
    Description: CIDR block for the public subnet, located in Availability Zone 2.
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/24
    Description: CIDR block for the private subnet, located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.192.0/24
    Description: CIDR block for the private subnet, located in Availability Zone 2.
    Type: String
  AvailabilityZones:
    Description: Select two Availability Zones for VPC subnets. The logical order of your selections is preserved in the deployment.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  BoomiUsername:
    Description: Boomi account username. Not required if using a Boomi installation token.
    Type: String
  BoomiPassword:
    Description: Boomi account password. Not required if using a Boomi installation token.
    Type: String
    NoEcho: true
  BoomiAccountID:
    Description: ID of the Boomi account to associate with the new Atom.
    Type: String
  BoomiInstallToken:
    Description: Boomi installation token.
    Type: String
    Default: ''
  BoomiInstallDir:
    Description: Boomi installation directory.
    Type: String
    Default: /opt/boomi/
  AtomName:
    Description: Boomi Atom instance name.
    Type: String
    Default: atom1
    AllowedPattern: "[a-zA-Z0-9_]*"
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart
    Description:
      Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription:
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-boomi-atom/
    Description:
      S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with a forward slash. 
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the instances. We recommend that you set this value to a trusted IP range.
    Type: String
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        NumberOfAZs: '2'
        VPCCIDR: !Ref VPCCIDR
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub
          - "https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template"
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        BastionAMIOS: 'Amazon-Linux2-HVM'
        KeyPairName: !Ref 'KeyPairName'
        PublicSubnet1ID: !GetAtt
          - VPCStack
          - Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt
          - VPCStack
          - Outputs.PublicSubnet2ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub "${QSS3KeyPrefix}submodules/quickstart-linux-bastion/"
        QSS3BucketRegion: !Ref QSS3BucketRegion
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !GetAtt
          - VPCStack
          - Outputs.VPCID
  BoomiAtomStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: 
          !Sub 
            - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/boomi-atom.template.yaml'
            - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
              S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
        Parameters:
          PrivateSubnet1ID: !GetAtt
            - VPCStack
            - Outputs.PrivateSubnet1AID
          BoomiUsername: !Ref 'BoomiUsername'
          BoomiPassword: !Ref 'BoomiPassword'
          BoomiAccountID: !Ref 'BoomiAccountID'
          BoomiInstallDir: !Ref 'BoomiInstallDir'
          AtomName: !Ref 'AtomName'
          BoomiInstallToken: !Ref 'BoomiInstallToken'
          BastionSecurityGroupID: !GetAtt
            - BastionStack
            - Outputs.BastionSecurityGroupID
          InstanceType: !Ref InstanceType
          BoomiInstanceVolumeSize: !Ref 'BoomiInstanceVolumeSize'
          VPCID: !GetAtt
            - VPCStack
            - Outputs.VPCID
          KeyPairName: !Ref 'KeyPairName'
Outputs:
  Postdeployment:
    Description: See the deployment guide for post-deployment steps.
    Value: https://aws.amazon.com/quickstart/?quickstart-all.sort-by=item.additionalFields.sortDate&quickstart-all.sort-order=desc&awsm.page-quickstart-all=5
