---
AWSTemplateFormatVersion: '2010-09-09'
Description: Boomi Atom Installation Script. This creates a VPC, Public Subnets and
  Private Subnets, and stages a Dell Boomi Atom. (qs-1r0e5j2b9)
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - VPCID
      - PrivateSubnet1ID
      - BastionSecurityGroupID
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - InstanceType
      - KeyPairName
      - BoomiInstanceVolumeSize
    - Label:
        default: Dell Boomi Atom configuration
      Parameters:
      - AtomName
      - BoomiAccountID
      - BoomiUsername
      - BoomiPassword
      - BoomiInstallToken
      - BoomiInstallDir
    ParameterLabels:
      KeyPairName:
        default: SSH key name
      VPCID:
        default: VPC ID
      InstanceType:
        default: Boomi Atom instance type
      BoomiInstanceVolumeSize:
        default: Amazon EBS volume size for Boomi Atom instance
      BoomiAccountID:
        default: Boomi account ID
      BoomiUsername:
        default: Boomi username
      BoomiPassword:
        default: Boomi password
      BoomiInstallToken:
        default: Boomi installation token
      PrivateSubnet1ID:
        default: Private subnet ID
      AtomName:
        default: Atom name
      BoomiInstallDir:
        default: Boomi install directory
Parameters:
  KeyPairName:
    Description: Key pair that allows you to connect securely to your instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be an existing name.
  BastionSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
  InstanceType:
    Description: Boomi host instance type.
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - m4.xlarge
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - r4.xlarge
      - r5.xlarge
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
  BoomiInstanceVolumeSize:
    Description: Size of the Amazon EBS volume attached to the Atom instance. Size range is 1GiB–16TiB.
    Type: Number
    Default: 100
  VPCID:
    Description: VPC to deploy into.
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1ID:
    Description: ID of the private subnet, in Availability Zone 1 in your existing VPC.
    Type: AWS::EC2::Subnet::Id
  BoomiUsername:
    Description: Boomi account username. (Not required if using a Boomi installation token.)
    Type: String
  BoomiPassword:
    Description: Boomi account password. (Not required if using a Boomi installation token.)
    Type: String
    NoEcho: true
  BoomiAccountID:
    Description: Boomi account ID to associate with the new Atom.
    Type: String
  BoomiInstallDir:
    Description: Boomi installation directory.
    Type: String
    Default: /opt/boomi/
  AtomName:
    Description: Boomi Atom instance name.
    Type: String
    Default: atom1
    AllowedPattern: "[a-zA-Z0-9_]*"
  BoomiInstallToken:
    Description: Boomi installation token.
    Type: String
    Default: ''
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      AMZNLINUX2: ami-0ce107ae7af2e92b5
    ap-northeast-2:
      AMZNLINUX2: ami-03b42693dc6a7dc35
    ap-south-1:
      AMZNLINUX2: ami-0e306788ff2473ccb
    ap-southeast-1:
      AMZNLINUX2: ami-015a6758451df3cb9
    ap-southeast-2:
      AMZNLINUX2: ami-0f96495a064477ffb
    ca-central-1:
      AMZNLINUX2: ami-0c2f25c1f66a1ff4d
    eu-central-1:
      AMZNLINUX2: ami-00a205cb8e06c3c4e
    eu-west-1:
      AMZNLINUX2: ami-0bb3fad3c0286ebd5
    eu-west-2:
      AMZNLINUX2: ami-0a669382ea0feb73a
    eu-west-3:
      AMZNLINUX2: ami-0de12f76efe134f2f
    sa-east-1:
      AMZNLINUX2: ami-02898a1921d38a50b
    us-east-1:
      AMZNLINUX2: ami-0947d2ba12ee1ff75
    us-east-2:
      AMZNLINUX2: ami-03657b56516ab7912
    us-west-1:
      AMZNLINUX2: ami-0e4035ae3f70c400f
    us-west-2:
      AMZNLINUX2: ami-0528a5175983e7f28
    eu-north-1:
      AMZNLINUX2: ami-0653812935d0743fe
    ap-east-1:
      AMZNLINUX2: ami-814d0ff0
    me-south-1:
      AMZNLINUX2: ami-08155c9ee8b845e35
    af-south-1:
      AMZNLINUX2: ami-0cec12e29ebe3f0d5
    eu-south-1:
      AMZNLINUX2: ami-0759301b88845d121
    ap-northeast-3:
      AMZNLINUX2: ami-024125eb5035fd485
    us-gov-east-1:
      AMZNLINUX2: ami-0e7e977f
    us-gov-west-1:
      AMZNLINUX2: ami-acbd84cd
    cn-north-1:
      AMZNLINUX2: ami-0f30329b403b2cd2f
    cn-northwest-1:
      AMZNLINUX2: ami-0b9e03ed3ef793940
Rules:
  PasswordOrMFAToken:
    Assertions:
      - Assert: !Or
          - !And
            - !Equals [!Ref BoomiPassword, '']
            - !Not [!Equals [!Ref BoomiInstallToken, '']]

          - !And
            - !Not [!Equals [!Ref BoomiPassword, '']]
            - !Equals [!Ref BoomiInstallToken, '']
        AssertDescription: You must supply either a password or an MFA installation token.
Conditions:
  InstallTokenProvided:  !Not [!Equals [!Ref BoomiInstallToken, '']]
Resources:
  AtomWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  AtomWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: !Ref 'AtomWaitHandle'
      Timeout: "900"
      Count: 1
  BoomiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: boomi
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: BoomiSG
      SecurityGroupIngress:
      - FromPort: 22
        IpProtocol: tcp
        SourceSecurityGroupId: !Ref BastionSecurityGroupID
        ToPort: 22
  AtomInstanceEBS:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref BoomiInstanceVolumeSize
      Encrypted: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: Atom
    DeletionPolicy: Snapshot
  AtomInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: Name
          Value: !Ref 'AtomName'
      ImageId:
        !FindInMap
        - AWSAMIRegionMap
        - Ref: AWS::Region
        - AMZNLINUX2
      InstanceType:
        Ref: InstanceType
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      NetworkInterfaces:
        - GroupSet:
            - !Ref BoomiSecurityGroup
          AssociatePublicIpAddress: false
          DeviceIndex: '0'
          DeleteOnTermination: true
          SubnetId: !Ref PrivateSubnet1ID
      Volumes:
        -
          Device: "/dev/xvdf"
          VolumeId: !Ref AtomInstanceEBS
      KeyName:
        Ref: KeyPairName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export PATH=$PATH:/usr/local/bin
          yum update -y 
          yum install git -y
          git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git /quickstart-linux-utilities
          cd /quickstart-linux-utilities
          source quickstart-cfn-tools.source
          qs_update-os
          qs_aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AtomInstance --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? '${AtomWaitHandle}'
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk: []
          files:
            /tmp/atom.service:
              content: !Sub |
                [Unit]
                Description=Dell Boomi Atom
                After=network.target
                RequiresMountsFor=/opt/boomi/Atom_${AtomName}
                [Service]
                Type=forking
                User=root
                Restart=always
                ExecStart=/opt/boomi/Atom_${AtomName}/bin/atom start
                ExecStop=/opt/boomi/Atom_${AtomName}/bin/atom stop
                ExecReload=/opt/boomi/Atom_${AtomName}/bin/atom restart
                [Install]
                WantedBy=multi-user.target
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            02_create_xfs:
              command: mkfs -t xfs /dev/nvme1n1 && mkdir /opt/boomi && sh -c 'echo "/dev/nvme1n1 /opt/boomi xfs defaults,noatime 0 0" >> /etc/fstab' && mount -a
            03_set_hostname:
              command: ln -sf /opt/boomi/Atom_$(curl http://169.254.169.254/latest/meta-data/local-hostname | sed -r 's/[-.]+/_/g')/jre/bin/java /usr/bin/java && . ~/.bash_profile
            04_set_perms_and_create_dir:
              command: cd /usr/local && sudo mkdir boomi && sudo chown ec2-user:ec2-user boomi && cd /usr/local/boomi
            05_get_installer:
              command: wget -P /usr/local/boomi https://platform.boomi.com/atom/atom_install64.sh && chmod +x /usr/local/boomi/atom_install64.sh
            06_create_installer_dir:
              command: !Sub sudo mkdir -p ${BoomiInstallDir} && sudo chown -R ec2-user:ec2-user ${BoomiInstallDir} && cd /usr/local/boomi
            07_start_installer:
              command: !If
                - InstallTokenProvided
                - !Sub |
                  echo "installing via token: /usr/local/boomi/atom_install64.sh -q console -VinstallToken=${BoomiInstallToken} -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}" && /usr/local/boomi/atom_install64.sh -q console -VinstallToken=${BoomiInstallToken} -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}
                - !Sub |
                  echo "installing via username/password: /usr/local/boomi/atom_install64.sh -q console -Vusername=${BoomiUsername} -Vpassword=******** -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}" && /usr/local/boomi/atom_install64.sh -q console -Vusername=${BoomiUsername} -Vpassword="${BoomiPassword}" -VatomName=${AtomName} -VaccountId=${BoomiAccountID} -dir ${BoomiInstallDir}
            08_create_service:
              command: mv /tmp/atom.service /lib/systemd/system/atom.service
            09_start_service:
              command: systemctl enable atom && systemctl start atom
  EcInstanceAutorecoverAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:automate:${AWS::Region}:ec2:recover
      AlarmDescription: Recover instance if its status checks fail.
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Dimensions:
        - Name: InstanceId
          Value: !Ref AtomInstance
      EvaluationPeriods: 2
      Period: 60
      Statistic: Minimum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
...
